[build]
  command = "npm run build"
  publish = ".output/public"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"